language: node_js
node_js:
- lts/*
cache: yarn
install: yarn
script: yarn test
deploy:
  provider: npm
  email: mariosant@sent.com
  api_key:
    secure: VFGESCFEAUU3eqTmVBtqpZc0J8NkRHg/5S14s1tcV13lrhwTyhIOk9Jn6x2o+XHkT8/yJhqZN3CLThaF/Isehv44EUEWM64lap5S8eHdmcbk7sSK0xi29E66jDTP0t1FqMsG3FcbLqiAYMX9t3wmptDhEJfHtPnauEixcr4lwTRHH6Pm0f6ZY2kgXZ+t1Cpxvk3wjxNyPsmd6w1E+cKm1O0ux/IH8RYHikBPJ+d6c6tjMMlGcwt9V+36Uv1LMSm97PCqVutgnEzVT1EhZ02CpeIZFevkW0z9pASNbse+pbM5xf8y2K3iRwcF8CDCywRpQOM+z3FliZZNlSMgZrSiifAB58J9owgzk9CAznPyDoCBA9Vu6jiDxaXd9sM+QoElqVHpy95WpjCTfZOgSxcsTX8clwAmTxlXw6Dhy09SS2a+9b+lfSAc3U6Mbi9QrxDnhRZW8jogqkqy5RockRgfNfx5RpiwvCSsIaxEp+0MewoMKGzbOTw2WHLiEsb22EhYcaA8gaR7l4fowvaHtNeP/Pz6NPz/mKGKvtPH2x7YDd6CDWkSfBMlDrTCmglXxCyXBdQXsXu0LHGgGQxM5VDe37cIZpNHAXr2iCGHd/40PStWGNf13EZ7iSuYt9kAp/wy6SexjqyEZhi/paeHMT3PSQQ3bd+kgQJt0R38HbMh+1s=
  on:
    tags: true
    repo: mariosant/react-wizard
